version: '3.8'
services:
  postgres:
    image: postgres:15 
    restart: always
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
