basePath: /api
definitions:
  entities.Task:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      priority:
        type: integer
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Esta API permite manejar tareas.
  title: Task API
  version: "1.0"
paths:
  /tasks/:
    get:
      description: Retorna todas las tareas registradas
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Task'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtener todas las tareas
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Crea una nueva tarea y la guarda en la base de datos
      parameters:
      - description: Datos de la tarea
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/entities.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.Task'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Crear una nueva tarea
      tags:
      - tasks
  /tasks/{id}:
    get:
      description: Retorna una tarea específica dado su ID
      parameters:
      - description: ID de la tarea
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Task'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtener una tarea por ID
      tags:
      - tasks
schemes:
- http
swagger: "2.0"
